import names
import random

def gerar_nome(genero="neutro"):
    etnias = ["Negro", "Branco", "Asiático", "Latino"]
    etnia = random.choice(etnias)
    
    if genero.lower() == "masculino":
        nome = names.get_first_name(gender='male')
    elif genero.lower() == "feminino":
        nome = names.get_first_name(gender='female')
    else:
        nome = names.get_first_name()
    
    sobrenome = names.get_last_name()
    return f"{nome} {sobrenome} ({etnia})"

# Dicionário de classes e trilhas dependentes com descrições
classes_trilhas = {
    "Combatente": {"descrição": "Guerreiros treinados para o campo de batalha.", "trilhas": {
        "Aniquilador": "Especialista em causar destruição em massa.",
        "Infantaria": "Soldado preparado para combates diretos.",
        "Fuzileiro": "Perito em armamento de fogo.",
        "Franco-atirador": "Mestre na arte do tiro de precisão.",
        "Tanque": "Resistente e focado em defesa.",
        "Conversor": "Capaz de manipular táticas para vantagem.",
        "Esgrimista": "Especialista no combate com lâminas.",
        "Duelsta": "Treinado para combates individuais.",
        "Exterminador": "Caçador de inimigos específicos.",
        "Devastador": "Focado em destruição total.",
        "Espadachin": "Mestre na arte da espada.",
        "Pistoleiro": "Letal com armas de fogo curtas."
    }},
    "Operador": {"descrição": "Estratégicos e versáteis em múltiplas funções.", "trilhas": {
        "Comandante": "Líder nato, coordena operações militares.",
        "Médico": "Especialista em curar e salvar vidas.",
        "Artífice": "Capaz de criar e reparar equipamentos.",
        "Engenheiro": "Domina tecnologias avançadas.",
        "Arqueiro": "Mestre em ataques de longa distância.",
        "Batedor": "Ágil e furtivo em missões de reconhecimento.",
        "Toxicologista": "Manipula venenos para vantagem tática.",
        "Cameramen": "Documenta e analisa situações.",
        "Demolidor": "Especialista em explosivos.",
        "Caçador": "Perseguidor nato de presas e inimigos.",
        "Infiltrador": "Mestre da furtividade e sabotagem."
    }},
    "Ocultista": {"descrição": "Manipuladores de forças sobrenaturais.", "trilhas": {
        "Graduado": "Detém conhecimentos ocultos avançados.",
        "Flagelador": "Utiliza dor para fortalecer sua magia.",
        "Conduíte": "Canaliza energias arcanas para variados usos.",
        "Xamã": "Mediador entre espíritos e humanos.",
        "Maldito": "Portador de uma maldição poderosa.",
        "Intuitivo": "Capta informações sobrenaturais.",
        "Sombraomante": "Manipula sombras para atacar e se esconder.",
        "Exorcista": "Expulsa entidades malignas.",
        "Lâmmina": "Guerreiro oculto especializado em lâminas encantadas.",
        "Mago": "Domina a magia em sua forma pura.",
        "Atroz": "Destruidor de forças divinas e infernais.",
        "Curandeiro": "Capaz de curar ferimentos místicos."
    }},
    "Psycho": {"descrição": "Guiados por instintos caóticos e imprevisíveis.", "trilhas": {
        "Fantasma": "Capaz de se esgueirar sem ser notado.",
        "Abatedor": "Sanguinário que se delicia na destruição.",
        "Cerqueiro": "Mestre da pressão psicológica.",
        "Palhaço": "Engana e confunde inimigos.",
        "Implacável": "Nunca recua de um confronto.",
        "Dissimulado": "Mestre do disfarce e manipulação.",
        "Bruxa": "Usuária de feitiços macabros.",
        "Doutor": "Brinca com a vida e a morte.",
        "Predador": "Caçador cruel e calculista.",
        "Piromaníaco": "Obcecado por fogo e destruição."
    }},
    "Híbrido": {"descrição": "Guiados por instintos caóticos e imprevisíveis.", "trilhas": {
        "Aberrante": "Capaz de se esgueirar sem ser notado.",
        "Assombração": "Sanguinário que se delicia na destruição.",
        "Feral": "Mestre da pressão psicológica.",
        "Mostro": "Engana e confunde inimigos.",
        "Abominação": "Nunca recua de um confronto.",
    }}

}

# Lista de origens disponíveis com descrições
origens = {
    "Abutre":"Perícias Treinadas: Investigação e Sobrevivência \nEspólios: No final de uma cena de combate, você pode incluir umitem encontrado na cena em seu inventário sem que ele conte em seu limite de itens. Você pode ter itens desse jeito igual sua AGI.",
    "Acadêmico":"Perícias Treinadas: Ciências e Investigação. \nSaber é Poder: Uma vez por rodada, quando faz um teste com Intelecto, você pode gastar 2 PE para receber +5 no teste e +1dado.", 
    "Açougueiro":"Perícias Treinadas: Percepção e Profissão. \nCorte Rápido: Você soma sua Agilidade testes de ataque e nas rolagens de dano em ataques com armas de corte e quando acerta um crítico no 20 em um teste de ataque, deixa o alvo sangrando por 2 rodadas.", 
    "Acupunturista":"Perícias Treinadas: Medicina e Tática. \nPontos de Pressão: Uma vez por pessoa por dia, pode curar 3d6 +INT de SAN e recebe +1 dado de dano do mesmo tipo com armas que causem dano de perfuração.", 
    "Adestrador":"Perícias Treinadas: Adestramento e Diplomacia. \nMelhor amigo da Onça: Você recebe +10 em domesticar e manejar animais e animais domesticados por você recebem +5 de Defesa, +2 em testes de ataque e rolagens de dano e +1 dado em testes de ataque.", 
    "Agricultor":"Perícias Treinadas: Diplomacia e Enganação. \nOBJEÇÃO: Uma vez por rodada, você pode fazer um aliado em alcance curto rolar novamente um teste.", 
    "Agente Secreto":"Perícias Treinadas: Furtividade e Enganação. \nZero Zero Sete: Você recebe proficiência com 3 gadgets operacionais a sua escolha e +2 de Defesa e testes enquanto ninguém sabe sua identidade real em alcance curto.",
    "Agiota":"Perícias Treinadas: Crime e Intimidação. \nCobrança: Você recebe +2 em testes para coagir, pode coagir com uma ação padrão e o alvo não consegue passar automaticamente, mas ainda pode ter bônus a critério do mestre. Caso passe, o alvo fica Abalado e você recebe 2 PEs temporários.", 
    "Agricultor":"Perícias Treinadas: Adestramento e Profissão. \nDeus do Trovão: Você recebe +5 em testes em testes envolvendo plantas e tem a DT de substâncias criadas com plantas aumentada em +2.", 
    "Alcóolatra":"Perícias Treinadas: Fortitude e Diplomacia. \nMc Rozi: Ao ficar com a condição Bêbado, recebe +1 dado e +2 em testes de resistência.", 
    "Alpinista":"Perícias Treinadas: Atletismo e Sobrevivência. \nBotas Verdes: Você recebe +2 em testes de escaladas, pode reduzir o espaço de um item em 1 e quando escala, avança seu deslocamento normal.", 
    "Alternativo":"Perícias Treinadas: Atualidades e Tecnologia. \nEu Sou Diferente: Você bônus de +5 em testes relacionados a coisas desconhecidas pela maioria da população.", 
    "Alquimista":"Perícias Treinadas: Ciências e Ocultismo. \nMetal Cheio: Você recebe +5 em testes relacionados a alquimia e substâncias criadas por você tem a DT aumentada em +2.", 
    "Amnésico":"Perícias Treinadas: Duas a critério do mestre. \nDeja Vu: Você pode fazer um teste de Intelecto (DT VARIA), se passar, recebe 1d4 +2 PE e uma informação útil relacionado ao seu passado, a critério do mestre.", 
    "Ajudante Braçal":"Perícias Treinadas: Fortitude e Profissão. \numa mão: Ao ajudar em testes com atributos físicos, você aumenta em +1 dado de atributo e +2 no teste auxiliado.",
    "Animador":"Perícias Treinadas: Artes e Percepção. \nQuadro de Impacto: Ao usar uma ação de movimento, pode fazer um desenho e receber +2 em uma perícia referente ao desenho feito até o final de uma rodada.",
    "Apostador":"Perícias Treinadas: Enganação e Intuição. \nJackpot: Uma vez por rodada durante uma cena de combate, ao tirar um crítico no 20 em um teste de perícia, você ganha 1d4+2 PE e SAN.", 
    "Apaixonado":"Perícias Treinadas: Diplomacia e Vontade.  \nSe Não For Pedir Demais: Você é apaixonado por 1 pessoa e recebe +1 dado e +2 em testes relacionados a essa pessoa.", 
    "Apocalíptico":"Perícias Treinadas: Tática e Vontade. \nO Fim Está Próximo: Você recebe +2 em testes contra o paranormal e recebe +1 dado de vontade em testes para reduzir dano mental pela metade.", 
    "Aprendiz":"Perícias Treinadas: Atualidades e Ciências. \nCorreria: Uma vez por cena, você pode gastar 2 PE para copiar o bônus de uma perícia de uma pessoa que tenha usado tal perícia.", 
    "Armeiro":"Perícias Treinadas: Pontaria e Profissão. \nSem Reembolsos: Uma vez por cena, você pode colocar um modificador extra, mesmo que a arma já tenha o modificador, em armas de fogo e munições com uma ação padrão, esse modificador dura 1d4 +INT rodadas.", 
    "Arqueiro":"Perícias Treinadas: Percepção e Pontaria. \nSiga a Seta: Você recebe +2 em testes e ataques e rolagens de dano com armas de Disparo, se for Veterano em Pontaria o bônus muda para +4 e se for Mestre muda para +6.", 
    "Arqueólogo":"Perícias Treinadas: Ciências e Investigação. \nRelíquias do Passado: Você pode reduzir a categoria e espaço em 1 de um item amaldiçoado e recebe +5 em testes para identificar usos e propósitos de itens.",
    "Assasino de Aluguel":"Perícias Treinadas: Furtividade e Reflexos. \nEvasão: Quando sofre um ataque que permite um teste de reflexos para reduzir o dano à metade, você não sofre dano algum se passar.", 
    "Assasino em Série":"Perícias Treinadas: Crime e Vontade. \nMato por prazer: Uma vez por dia, você pode gastar uma ação de movimento e escolher uma pessoa, você recebe +2 em testes de ataque contra ela e se realizar um acerto crítico, você pode gastar 2 PE para ter o dano do ataque maximizado, caso mate ela na cena, recebe 2d6 +2 de SAN e PE.", 
    "Astronauta":"Perícias Treinadas: Fortitude e Tecnologia. \nInterestelar: Você recebe resistência a dano mental igual a seu Intelecto, +5 em testes de Tecnologia e +2 em testes de resistência contra efeitos mundanos.", 
    "Ativista":"Perícias Treinadas: Atualidades e Vontade. \nTudo Pela Causa: Uma vez por cena, caso seja reduzido a 0 ou menos de PV ou de SAN faça um teste de Presença DT 15 se passar fica com 1 de PV ou 1 de SAN.", 
    "Ator":"Perícias Treinadas: Diplomacia e Enganação. \nPor Trás da Máscara Você recebe +2 em testes de Diplomacia, Enganação e Intimidação.", 
    "Autodidata":"Perícias Treinadas: Duas a seu critério. \nEu Que Aprendi: Você recebe+2 com as perícias de sua origem e uma vez por cena pode gastar 2 PE para ficar treinado em uma perícia até o final da cena.",
    "Avoado":"Perícias Treinadas: Percepção e Vontade. \nHan? Repete: Uma vez por cena, você pode se infligir com a condição Avoado por PRE+1 rodadas como ação livre.", 
    "Bancheiro":"Perícias Treinadas: Profissão e Tática. \nRenda Extra: Você recebe +5 em testes que envolvam dinheiro e pode mentir com Profissão.", 
    "Barbeiro":"Perícias Treinadas: Profissão e Tecnologia. \nO Pé: Você pode fazer cortes de cabelo igual a seu INT por dia, pessoas que tiverem seu cabelo cortado por você recebem +1 dado e +2 em testes de Presença até ficarem machucados.", 
    "Bartender":"Perícias Treinadas: Intuição e Profissão. \nMe vê um Drink: Consumidores da sua bebida recebem +1 dado de Presença até o final da próxima cena, caso a bebida possua algum efeito, aumenta a DT para resistir em +5.", 
    "Bicheiro":"Perícias Treinadas: Crime e Tática. \nDono do Jogo: Uma vez por cena, quando rola um dado que seja um erro crítico você pode transformar em um crítico no 20.", 
    "Bombeiro":"Perícias Treinadas: Fortitude e Iniciativa. \nCoragem Ardente: Você recebe RD Fogo 5 e +2 em testes de resistência e Defesa.", 
    "Caçador":"Perícias Treinadas: Percepção e Sobrevivência. \nArapuca: Você soma seu bônus de Sobrevivência na DT de armadilhas e quando ataca um animal desprevenido com um ataque a distância, maximiza o dano do ataque.", 
    "Caçador de Recompensas":"Perícias Treinadas: Percepção e Tática. \nCabeça a Prêmio: Você pode rastrear com Percepção e pode uma vez por cena, gastar uma ação de movimento pra marcar uma pessoa como seu alvo, recebendo +1 no multiplicador de crítico contra ela.", 
    "Cantor":"Perícias Treinadas: Artes e Fortitude. \nA Voz de um Anjo: Você pode tirar de enlouquecendo com Artes em alcance curto e uma vez por cena pode cantar e curar 3d6 +PRE de SAN de todos seres em alcance curto.", 
    "Cavaleiro":"Perícias Treinadas: Luta e Tática. \nCódigo de Honra: Você recebe +2 em testes de ataque e rolagens de dano com armas medievais, recebe +1 dado de dano do mesmo tipo em armas medievais corpo a corpo e recebe +2 em testes de resistência contra criaturas.", 
    "Charlatão":"Perícias Treinadas: Crime e Enganação.  \nVendedor de Susto: Você pode gastar 2 PE para substituir um teste de perícia qualquer, exceto testes de ataque e resistência, por um teste de Enganação.", 
    "Chef":"Perícias Treinadas: Fortitude e Profissão. \nDeixa Eu Cozinhar: Uma vez por dia, você pode fazer um teste de Profissão, o tempo que você passa cozinhando é igual a 90-teste de Profissão minutos, quando termina, cozinha sua refeição e deixa pessoas que consumirem sua comida com PE temporário igual a seu teste de Profissão até o fim da próxima cena.", 
    "Cientista":"Perícias Treinadas: Ciências e Profissão. \nEureka: Você pode substituir um teste de Diplomacia e Vontade por um teste de Ciências, a DT de seus itens é aumentada em +2.",
    "Circense":"Perícias Treinadas: Acrobacia e Artes. \nDe Solé: Uma vez por cena, ao gastar 4 PE e uma ação completa, você faz um espetáculo que dura 1d4+1 rodadas, durante o espetáculo você recebe +5 de Defesa e aliados em alcance curto recebem +1 dado em testes de perícia, para manter o espetáculo ativo é necessário usar uma ação padrão toda rodada.", 
    "CLT":"Perícias Treinadas: Profissão e Vontade. \nSegunda a Sexta: Quando faz um teste de perícia, você pode gastar 1 PE para receber +2 nesse teste.", 
    "Coach":"Perícias Treinadas: Diplomacia e Tática. \nQUEM VAI CARREGAR OS BARCOS: Uma vez por cena, você pode gastar uma ação padrão para que todos os seres com consciência em um raio de 15 metros recebam +2 em todos os testes até o fim da cena.", 
    "Comandante":"Perícias Treinadas: Diplomacia e Tática. \nMEUS SOLDADOS, AVANCEM: Uma vez por cena, pode gastar 5 PE e uma ação completa para conceder +5 em testes de ataque e resistência por 1 rodada.", 
    "Comediante":"Perícias Treinadas: Artes e Diplomacia.  \nSua Mãe: Uma vez por cena, ao fazer uma ação padrão e gastar 3 PE, você conta uma piada, fazendo com que todos os seres em alcance curto recebam 2d6 +5 de SAN caso achem engraçado.", 
    "Comentarista":"Perícias Treinadas: Percepção e Reflexos. \nNarrador de Enchente: Você pode usar uma reação no início do turno de um inimigo para narrar o que um inimigo vai fazer, caso esse inimigo for atacar, os afetados recebem +5 de Defesa e em testes de resistência até o turno inimigo acabar. Se seu aliado estava desprevenido, ele perde essa condição.", 
    "Comerciante":"Perícias Treinadas: Diplomacia e Intuição. \nVender o Peixe: Você recebe +5 em testes que esteja tentando negociar com um ser com consciência.",
    "Cosplayer":"Perícias Treinadas: Artes e Vontade.  \nNão É Fantasia, É Cosplay: Você pode fazer testes de disfarce usando Artes em vez de Enganação e recebe +2 em testes de perícia que tenham relação com o disfarce.", 
    "Coveiro":"Perícias Treinadas: Intimidação e Vontade.  \nPuxar seu Pé: Você recebe RD Mental 3 e consegue percorrer seu deslocamento normal em estado morrendo.", 
    "Craque":"Perícias Treinadas: Atletismo e Reflexos.  \nOlééé: Você pode fintar com um teste de Reflexos, ao fazer um teste para fintar, pode gastar 2 PE para receber +5 no teste e recebe +2 em testes de Reflexos.", 
    "Cultista":"Perícias Treinadas: Ocultismo e Vontade. \nCrença de culto: Você aprende 1 ritual de 1° círculo a sua escolha, sem precisar de componentes ritualísticos para realizar somente esse ritual.", 
    "Dançarino":"Perícias Treinadas: Artes e Reflexos. \nDança Padrão: Você recebe +5 na ação dançar e ao gastar 2 PE, pode substituir um teste de Reflexos por um teste de Artes.", 
    "Desgarrado":"Perícias Treinadas: Fortitude e Sobrevivência. \nVida na Margem: Você recebe +3 em deslocamento e testes de resistência contra coisas que afetem o seu corpo.", 
    "Detetive":"Perícias Treinadas: Investigação e Percepção. \nMeu Caro Watson: Você pode substituir testes de Intuição por testes de Investigação e recebe+5 nesses testes substituídos.",
    "Devoto":"Perícias Treinadas: Ocultismo e Religião. \nMacumba: Uma vez por dia pode fazer algum ritual de sua religião, você recebe 5 pontos de sanidade temporários e +2 em testes de ocultismo até o final da próxima cena.", 
    "Dublê":"Perícias Treinadas: Fortitude e Enganação. \nNem Doeu: Uma vez por cena, quando sofrer dano mundano, você pode gastar uma reação e 3 PE para anular esse dano e efeitos provenientes dele.", 
    "Enfermeiro":"Perícias Treinadas: Medicina e Profissão. \nChamado da Enfermeira: Você cura SAN de um ser que esteja curando igual a seu Intelecto toda vez que cura por meios mundanos.", 
    "Escritor":"Perícias Treinadas: Artes e Atualidades. \nEu Lírico: Uma vez por cena, você pode gastar 2 PE para se tornar treinado em uma perícia qualquer até o fim da cena.", 
    "Escritor Paranormal":"Perícias Treinadas: Atualidades e Ocultismo. \nBestiário: Ao realizar um teste de “Identificar Criatura” e passar, você e seres em alcance curto a sua escolha ganham um bônus de +2 em testes de resistência contra essa criatura.", 
    "Espião":"Perícias Treinadas: Enganação e Furtividade. \nLogo Atrás de Você: Uma vez por rodada, você pode gastar 2 PE para refazer um teste de Furtividade.", 
    "Estagiário":"Perícias Treinadas: Profissão e Vontade. \nJovem Aprendiz: Você pode gastar 2 PE para receber +2 e 1d4 extra no resultado de qualquer teste de perícia.",
    "Estilista":"Perícias Treinadas: Artes e Profissão. \nPingar: Você pode vestir +1 vestimenta e aumenta os bônus de perícias causados por vestimentas em +1.", 
    "Estóico":"Perícias Treinadas: Intimidação e Vontade. \nÉ o que É: Você recebe RD Mental igual a seu Limite de PE +PRE e recebe +2 em testes contra efeitos de Medo.", 
    "Exterminador de Pragas":"Perícias Treinadas: Ciências e Vontade. \nMalditos Insetos: Você causa dano maximizado em seres minúsculos e a DT de seus venenos aumenta em +2.", 
    "Explorador":"Perícias Treinadas: Investigação e Sobrevivência. \nLadrão de Tumbas: Você não sofre penalidade em deslocamento por terreno difícil e recebe +5 em testes para testes de Analisar Terreno e caso passe, recebe +5 em testes de resistência no ponto de vantagem.", 
    "Fã":"Perícias Treinadas: Vontade e uma relacionada a sua fixação. \nFã Número Um: Você recebe +1 dado e +5 em testes que envolvam sua fixação, esse bônus não serve para testes de ataques ou de resistência.", 
    "Faz-Tudo":"Perícias Treinadas: Profissão e Tecnologia. \nPau Pra Toda Obra: Você recebe +2 em perícias que não seja treinado e na sua capacidade de carga.",
    "Ferreiro":"Perícias Treinadas: Fortitude e Profissão. \nFogo e Ferro: Você pode colocar um modificador extra em armas corpo a corpo e de arremessos com uma ação padrão, mesmo que a arma já tenha o modificador, esse modificador dura 1d4 +1 rodadas.", 
    "Fisiculturista":"Perícias Treinadas: Atletismo e Fortitude. \nNatural, Vegano e Alérgico a Água: Você recebe +2 em testes com atributo-primário de força e +5 na sua capacidade de carga.", 
    "Flanelinha":"Perícias Treinadas: Artes e Iniciativa. \nSinal Fechado: Você recebe +2 em testes de Iniciativa e uma vez por cena pode refazer um teste de Iniciativa, caso seja o primeiro na ordem de iniciativa, recebe +2 em qualquer teste.", 
    "Fotógrafo":"Perícias Treinadas: Artes e Percepção. \nDIGA XIS: Você recebe +5 em testes de Investigação e Percepção se estiver olhando através de uma câmera.", 
    "Gamer":"Perícias Treinadas: Tecnologia e Reflexo. \nDeus Gamer: Você recebe +5 de Defesa contra inimigos que já te atacaram pelo menos uma vez na cena.", 
    "Garçom":"Perícias Treinadas: Atualidades e Diplomacia. \nAnota a Placa: Você recebe +2 dados em testes para lembrar de algo que já viu.", 
    "Gênio":"Perícias Treinadas: Atualidades e Ciências. \nEinstein é uma fraude: Você recebe +2 em testes com atributo primário de INT e adiciona seu INT no seu limite de PE.",
    "Ginasta":"Perícias Treinadas: Acrobacia e Reflexos. \nCruz Azariana: Você recebe +2 na Defesa e em testes de Reflexos, recebe +1 PE por NEX e pode escalar e saltar com Acrobacia.", 
    "Gigolô":"Perícias Treinadas: Diplomacia e Intuição. \nComedor de Casadas: Você recebe +5 em testes para seduzir uma pessoa e +5 em testes para se esconder de pessoas que conheçam a pessoa seduzida.", 
    "Guarda-Costas":"Perícias Treinadas: Percepção e Reflexos. \nSenhor Presidente: Uma vez por rodada, quando for se interpor a um aliado, você pode gastar 2 PE para receber 15 de RD ao dano que o aliado sofreria.", 
    "Hacker":"Perícias Treinadas: Crime e Tecnologia. \nParede de Fogo: Você recebe +10 em testes para invadir sistemas tecnológicos e pode substituir um teste de Diplomacia por um teste de Tecnologia uma vez por conversa.", 
    "Herói":"Perícias Treinadas: Iniciativa e Vontade. \nHomem Estrela: Você recebe +2 em Defesa, testes de resistência e RD a dano, incluindo mental. Ademais, sempre que se interpõe, recebe 10 de RD a dano contra o dano sofrido e 3 PVs temporários.", 
    "Humanitário":"Perícias Treinadas: Medicina e Vontade. \nCruz Vermelha: Você recebe 2d6 +3 de SAN toda vez que tira alguém de morrendo e +2 em testes de Vontade.", 
    "Ídolo":"Perícias Treinadas: Artes e Diplomacia. \nPoder de Estrela: Você recebe +5 em testes com atributo- primário de presença contra seres que conhecem você, pode usar Artes para tirar de enlouquecendo em alcance curto e recebe +2 em testes de Artes, Diplomacia e Enganação.",
    "Influenciador":"Perícias Treinadas: Atualidades e Diplomacia. \nAlgoritmo: Uma vez por dia, quando tiver acesso a internet, você pode rolar 1d20, resultado de 1 a 5, você perde seu Limite de PE +5 em sanidade, de 6 a 10 você perde metade do seu Limite de PE +2 em sanidade, de 11 a 15 você recupera seu Limite de PE +2 em sanidade e de 16 a 20 você recupera o dobro do seu Limite de PE +5 em sanidade.", 
    "Juiz":"Perícias Treinadas: Diplomacia e Intuição. \nA Justiça é Cega: Você recebe +5 em testes de Intuição para detectar mentiras e seres tem -2 em testes de ataque contra você.", 
    "Jornalista":"Perícias Treinadas: Atualidades e Diplomacia. \nEu Tô Ligado: Uma vez por conversa, você pode substituir um teste de Enganação ou Diplomacia por um de Atualidades.", 
    "Ladrão":"Perícias Treinadas: Crime e Furtividade.  \nMão Leve: Você recebe +5 em testes para roubar alguém e pode uma vez por conversa trocar um teste de Enganação por Crime.", 
    "Ladrão de Banco":"Perícias Treinadas: Crime e Tática. \nDia de Pagamento: Uma vez por dia, você e seres a sua escolha em alcance curto recebem +5 de Iniciativa, durante essa cena de combate vocês recebem +2 em testes de fortitude.", 
    "Legista":"Perícias Treinadas: Investigação e Medicina. \nPost Mortem: Você recebe RD Mental 3+INT contra cenários que envolvam corpos de pessoas e quando faz um teste de Medicina para necropsia, você recebe +5 nesse teste.",
    "Lenhador":"Perícias Treinadas: Fortitude e Sobrevivência. \nPica Pau: Você recebe +1 dado de dano do mesmo tipo e +2 em testes de ataque com armas corpo a corpo de duas mãos e causa dano maximizado com essas armas contra objetos.", 
    "Líder":"Perícias Treinadas: Diplomacia e Tática. \nPuxa o Esquadrão: Uma vez por rodada, você pode dar uma ordem para seus aliados, seus aliados recebem +2 em testes para cumprir a ordem.", 
    "Lutador":"Perícias Treinadas: Luta e Reflexos. \nManda o Jab: Você recebe +1 dado de dano do mesmo tipo em ataques desarmados e recebe+5 em rolagens de dano de ataques desarmados.", 
    "Magnata":"Perícias Treinadas: Diplomacia e Profissão. \nAndar do Milionário: Ao realizar um teste de Diplomacia, Enganação ou Intimidação você pode gastar 2 PE para receber +5 no teste.", 
    "Mafioso":"Perícias Treinadas: Crime e Diplomacia. \nPela Família: Você pode substituir testes de Intimidação por testes de Crime e recebe +5 em testes de ataque e rolagens de dano contra pessoas que estejam contra a sua organização.", 
    "Mágico":"Perícias Treinadas: Artes e Ocultismo. \nTruque na Manga: Uma vez por cena, você pode conjurar um ritual que não conheça, mas que possua os pré-requisitos como uma ação de movimento, caso o ritual tenha um teste de vontade oposto para resistir aos efeitos negativos, aumenta a DT em +5.", 
    "Mateiro":"Perícias Treinadas: Percepção e Sobrevivência. \nRoça: Desde que possa ver o céu, você consegue chegar sem se perder em qualquer lugar que já tenha visitado ao menos uma vez e pode gastar 2 de PE para refazer um teste de Sobrevivência.", 
    "Maratonista":"Perícias Treinadas: Atletismo e Iniciativa. \nSebo nas Canelas: Você recebe +3m de deslocamento e adiciona seu bônus de Atletismo na distância percorrida na ação correr.",
    "Marinheiro":"Perícias Treinadas: Atletismo e Vontade.  \nMal Presságio: Você recebe +5 em testes de resistência para resistir condições mentais e de medo.", 
    "Mecânico":"Perícias Treinadas: Profissão e Tecnologia. \nLata Velha: Você pode substituir testes de Tecnologia por Profissão caso o teste envolva algo físico e adiciona seu INT no seu Limite de PE.", 
    "Médico":"Perícias Treinadas: Intuição e Medicina. \nO Bom Doutor: Sempre que cura uma pessoa, você adiciona seu Intelecto no total de PV curados e sempre que você tira alguém do morrendo, ela recebe 2d6 +INT de PV.", 
    "Mercenário":"Perícias Treinadas: Iniciativa e Tática. \nTudo Tem Um Preço: Você recebe +1 no seu limite de PE por turno e no seu primeiro turno de cada cena de combate, você pode gastar 2 PE para receber uma ação de movimento adicional.", 
    "Mergulhador":"Perícias Treinadas: Atletismo e Fortitude. \nGrande Azul: Você pode prender a respiração por um número de rodadas igual ao dobro do seu Vigor, recebe +5 em testes de Atletismo para nadar e avança seu deslocamento normal nadando.", 
    "Mestre de RPG":"Perícias Treinadas: Intuição e Diplomacia.  \nRoteiro: Uma vez por cena, pode gastar 3 PE para ganhar +15 em um teste de perícia.",
    "Militar":"Perícias Treinadas: Pontaria e Tática. \nMissão Dada: Você recebe +1 dado de dano do mesmo tipo comarmas de fogo e +5 em rolagens de dano com armas de fogo.", 
    "Minerador":"Perícias Treinadas: Fortitude e Profissão.  \nDiamantes: Você recebe +2 em testes de fortitude e toda vez que você passar em um teste de fortitude, recebe +15 de PVs temporários", 
    "Modelo":"Perícias Treinadas: Intuição e Sobrevivência.  \nCharme: Uma vez por cena, você pode gastar 2 PE para fazer um teste de Diplomacia contra um teste de Vontade de uma pessoa se passar, a DT de tudo que essa pessoa exija que você faça tem sua DT diminuída em um valor igual à sua Presença +5.", 
    "Mochileiro":"Perícias Treinadas: Intuição e Sobrevivência. \nAbrir o Inventário: Você dobra a capacidade de carga de mochilas, diminui a categoria de mochilas em -1 e aumenta a sua capacidade de carga igual a aliados em alcance curto.", 
    "Monge":"Perícias Treinadas: Fortitude e Vontade. \nPaz de Espirito: Uma vez por cena, você pode meditar como uma ação completa para remover todas condições de medo e mentais que estejam lhe afetando e recuperar uma quantidade de pontos de SAN igual ao seu Limite de PE +PRE.", 
    "Motorista":"Perícias Treinadas: Pilotagem e Reflexos. \nEu Dirijo: Você recebe +1 dado e +2 em testes de perícias enquanto estiver em um veículo em movimento e soma seu bônus de Pilotagem no deslocamento do veículo.", 
    "Muquirana":"Perícias Treinadas: Diplomacia e Sobrevivência. \nMão de Vaca: Você pode usar qualquer item mundano de uso único uma segunda vez por item.", 
    "Ninja":"Perícias Treinadas: Acrobacia e Furtividade. \nShinobi: Você pode escalar com testes de Acrobacia com o seu deslocamento normal, recebe +2 em testes de Furtividade e quando for receber dano de queda, recebe o dano pela metade.", 
    "Nobre":"Perícias Treinadas: Atualidades e Diplomacia. \nSangue Azul: Você recebe +5 em testes de Diplomacia, Enganação e Intimidação contra pessoas que conheçam sobre a sua família ou de algum membro da sua família.",
    "Operário":"Perícias Treinadas: Fortitude e Profissão. \nFerramenta de Trabalho: Escolha uma arma que, a critério do mestre, poderia ser usada como ferramenta em sua profissão. Você sabe usar a arma escolhida e recebe +2 em testes de ataque, rolagens de dano e margem de ameaça com ela.",
    "Otimista":"Perícias Treinadas: Diplomacia e Vontade.  \nVamos Conseguir: Uma vez por cena, ao gastar uma ação de movimento você faz com que aliados em alcance curto recebam +1 dado e +5 em testes de vontade até o fim da cena.", 
    "Pacifista":"Perícias Treinadas: Diplomacia e Enganação. \nEu Não Tenho Inimigos: Você recebe +1 dado em testes de Diplomacia e Intuição e todo dano mundano que você causa conta como dano não letal.", 
    "Padre":"Perícias Treinadas: Religião e Vontade. \nNão Tema: Você recebe RD Mental igual a sua Presença, recebe +5 em testes de Religião para acalmar e quando acalma uma pessoa, ela recebe 2d6 +2 de SAN.", 
    "Palhaço":"Perícias Treinadas: Artes e Diplomacia. \nPor que tão sério: Você pode usar Artes para tirar de enlouquecendo e uma vez por cena, pode curar 3d6 +4 de SAN de um aliado em alcance curto.", 
    "Paramédico":"Perícias Treinadas: Iniciativa e Medicina. \nPrimeiros Socorros: Uma vez por cena, quando um aliado no seu deslocamento entrar em estado machucado, você pode gastar uma ação livre para se deslocar até ele e restaurar 3d6 +INT pontos de vida ao alvo.", 
    "Pescador":"Perícias Treinadas: Pontaria e Sobrevivência. \nCaiu na Isca: Você é imune a condição de terreno difícil gerados por líquidos e recebe +5 em testes para fintar, prender, amarrar ou se segurar.", 
    "Pintor":"Perícias Treinadas: Artes e Percepção. \nOlhar de Pintor: Você pode trocar testes de Percepção por um teste de Artes e recebe +2 em testes de Artes.",
    "Pirata":"Perícias Treinadas: Crime e Sobrevivência. \nMar de Ladrões: Você recebe +5 em testes para roubar e pode realizar manobras de combate com testes de Crime.", 
    "Policial":"Perícias Treinadas: Percepção e Pontaria. \nEu Temo Pela Minha Segurança: Você recebe +2 em Defesa e +2 em testes de resistência.", 
    "Político":"Perícias Treinadas: Diplomacia e Enganação. \nTeatro Das Tesouras: Você recebe +5 em testes que envolvam chantagear, subornar, manipular, enganar ou convencer uma pessoa e recebe RD Mental igual ao seu intelecto.", 
    "Prisioneiro":"Perícias Treinadas: Crime e Vontade. \nAlvará de Soltura: Você recebe +5 em testes contra a manobra agarrar e +2 em testes de resistência contra efeitos que afetam seu movimento de qualquer jeito.", 
    "Prodígio":"Perícias Treinadas: Fortitude e Vontade. \nTrabalhar duro: Você recebe +1 PV e PE a cada NEX, seu limite de PE por turno aumenta em +1 e recebe -1 em qualquer teste.", 
    "Professor":"Perícias Treinadas: Atualidades e Ciências. \nMeus Alunos: Uma vez por cena, pode gastar uma ação padrão e 2 PE para fornecer +1 em um atributo de outro aliado em alcance curto até o fim da cena.", 
    "Programador":"Perícias Treinadas: Investigação e Tecnologia. \nTrabalho Computaria: Sempre que tiver acesso rápido a internet, você pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Tecnologia.", 
    "Prostituta":"Perícias Treinadas: Fortitude e Diplomacia. \nProfissional do Esquecimento: Você recebe +1 dado e+5 em testes com atributo-primário de Presença contra seres que se sentem atraídos por você.",
    "Psiquiatra":"Perícias Treinadas: Ciências e Profissão. \nPílulas Felizes: Uma vez por rodada, você pode tirar um aliado adjacente do estado enlouquecendo como ação livre, porém o aliado perde 2 de sanidade permanente.", 
    "Psicólogo":"Perícias Treinadas: Intuição e Vontade. \nSai Dessa: Uma vez por rodada, você pode gastar uma ação padrão e 2 PE para remover uma condição mental de uma pessoa adjacente.", 
    "Químico":"Perícias Treinadas: Ciências e Profissão. \nQuebrando Mal: Os seus Antídotos podem ser consumidos com uma ação livre e a DT para resistir a qualquer substância fabricada por você aumenta em +2.", 
    "Radical":"Perícias Treinadas: Acrobacia e Vontade. \nIsso é Radical: Sempre que desvia de um ataque ou passa em um teste de resistência, recebe 3 PEs temporários e SAN.", 
    "Rebelde":"Perícias Treinadas: Iniciativa e Vontade. \nVou Fazer do Meu Jeito: Você recebe +5 em testes de resistência contra coisas que estejam tentando te alterar de qualquer jeito.", 
    "Reencarnado":"Perícias Treinadas: 2 perícias do antigo personagem. \nSegunda Chance: Você pode escolher começar com um Poder Paranormal, uma Habilidade de Classe ou o Poder de Origem de sua antiga vida, ignorando pré-requisitos.", 
    "Repórter":"Perícias Treinadas: Atualidades e Investigação. \nGrandes Notícias: Você pode substituir testes de Diplomacia por testes de Investigação e recebe +5 em testes de interrogar.",
    "Samurai":"Perícias Treinadas: Luta e Vontade. \nInvencível Sob o Sol: Você recebe +1 dado do mesmo tipo de dano em armas de corte e +2 em testes de resistência enquanto está empunhando uma arma de corte.", 
    "Skatista":"Perícias Treinadas: Acrobacia e Reflexos. \nCHORÃO: Enquanto estiver andando de skate, pode fazer testes de ataques corpo a corpo e manobras com Acrobacia e recebe +2 em testes de manobra.", 
    "Solitário":"Perícias Treinadas: Furtividade e Vontade. \nMal acompanhado: Você recebe +2 na Defesa, em testes de perícias e em seu limite de PE por turno se nenhum aliado estiver em alcance curto.", 
    "Streamer":"Perícias Treinadas: Diplomacia e Tecnologia. \nCHAT: Uma vez por rodada, você pode fazer um teste de Intelecto (DT VARIA) antes de fazer um teste de perícia, se passar, recebe uma informação útil para ajudar no teste, recebendo +2 no teste.", 
    "Tatuador":"Perícias Treinadas: Artes e Tecnologia. \nMáquina de Tinta: Você pode fazer um teste de Tecnologia, o tempo que passa tatuando é igual a 90-teste minutos, você pode tatuar igual sua PRE e tatuar rituais que tenha os pré-requisitos, se a tatuagem for um ritual, o ritual pode ser usado com uma ação de movimento, a tatuagem dissipa após o ritual ser utilizado.", 
    "Templário":"Perícias Treinadas: Religião e Vontade. \nDeus Vult: Você pode fazer testes de ataque corpo a corpo com Religião e recebe +2 em testes de vontade.", 
    "Torturador":"Perícias Treinadas: Investigação e Medicina. \nGrita Mais: Uma pessoa que sofrer dano de um ataque corpo a corpo seu perde -2 em testes de resistência e Defesa, esse bônus não é acumulativo.",
    "Traçeado":"Perícias Treinadas: Atletismo e Iniciativa. \nMiranha: Você pode subir por paredes, muros e obstáculos sem como parte do seu deslocamento normal e recebe dano de queda pela metade.", 
    "Traficante":"Perícias Treinadas: Crime e Intimidação. \nCaiu Na Vila: Você recebe +5 em testes de resistência contra drogas e uma vez por rodada, ao gastar 3 PE, você pode realizar um ataque como ação livre contra um inimigo caído.", 
    "Traído":"Perícias Treinadas: Atualidades e Investigação. \nCorno: Você recebe +1 PE a cada NEX ímpar e recebe +1 no seu Limite de PE.", 
    "Traumatizado":"Perícias Treinadas: Intuição e Vontade. \nPassou Por Coisas: Você recebe RD mental 3 +PRE e uma vez por cena, pode remover a condição Enlouquecendo de si próprio ao usar 5 PE, voltando com 1d6 +PRE de SAN.", 
    "Treinador":"Perícias Treinadas: Atletismo e Tática. \nBora Monstro: Uma vez por rodada, você pode gastar 2 PE para conceder um bônus de +1d6 ao resultado de um teste de perícia de um aliado em alcance curto.", 
    "Tribal":"Perícias Treinadas: Sobrevivência e Vontade. \nÍndio Fura: Se alguém importante para você for atacado à alcance curto de você, pode atacar o atacante com um ataque a distância sofrendo -1 dado de ataque.", 
    "Turista":"Perícias Treinadas: Atualidades e Percepção. \nLembrancinhas: Você recebe +2 em testes de Atualidades ou Percepção dentro de lugares que passou na sua vida por menos de um dia.",
    "Universitário":"Perícias Treinadas: Atualidades e Investigação. \nEstudante tem mais: Você recebe +1 PE a cada NEX ímpar e recebe +1 no seu limite de PE por turno aumenta em 1.", 
    "Vagabundo":"Perícias Treinadas: Atualidades e Intuição. \nA Mimir: Você pode dormir em qualquer lugar ou situação, tendo sua condição de descanso sempre uma categoria maior e ganhos por descanso dobrados.", 
    "Vigia":"Perícias Treinadas: Intuição e Percepção. \nVer por Cima: Você enxerga no escuro, ignora cobertura e recebe +2 em testes de Percepção.", 
    "Vilão":"Perícias Treinadas: Intimidação e Vontade. \nEu Sacrifico: Você recebe +2 em suas DTs, testes de resistência e testes sociais e quando assusta um alvo, ele fica pasmo por 1 rodada e sofre 3d6 +PRE de dano mental.", 
    "Xerife":"Perícias Treinadas: Iniciativa e Pontaria. \nSeis Balas: No seu primeiro turno de cada cena de combate, você pode gastar 3 PE para fazer um ataque a distância como ação livre.", 
    "Zelador":"Perícias Treinadas: Percepção e Profissão. \nLevanta o pé: Você pode substituir testes de Investigação por testes de Profissão e recebe +5 nesses testes.",
}

# Escolha aleatória de atributos do personagem
origem_escolhida = random.choice(list(origens.keys()))
classe_escolhida = random.choice(list(classes_trilhas.keys()))
trilha_escolhida = random.choice(list(classes_trilhas[classe_escolhida]["trilhas"].keys()))

# Exibir as escolhas do usuário com descrições
print("\nResumo do personagem:")
print(f"Origem: {origem_escolhida} - {origens[origem_escolhida]}")
print(f"\nClasse: {classe_escolhida} - {classes_trilhas[classe_escolhida]['descrição']}")
print(f"Trilha: {trilha_escolhida} - {classes_trilhas[classe_escolhida]['trilhas'][trilha_escolhida]}")
print(f"Nome do Personagem: {gerar_nome()}")
